config(vitest): add vitest through pnpm
pb-iot/frontend pull request #21
Opened 2023-10-11 10:14 UTC by SiwyKot41

Dodanie konfiguracji vitest do testów jednostkowych

2023-10-11 22:13 UTC, wvffle requested changes
Fajnie, ale nie dodales package.json i lockfile

2023-10-12 14:25 UTC, wvffle approved these changes

2023-10-17 10:33 UTC, SiwyKot41 commented
@Monikaa1909  @OlaWrobe  Prosiłbym o review

2023-10-17 13:07 UTC, Monikaa1909 approved these changes

2023-10-17 13:10 UTC, merged