add: pages reset&change password
pb-iot/frontend pull request #25
Opened 2023-10-17 11:29 UTC by jwroblewska

2023-10-17 12:09 UTC, SiwyKot41 submitted a review, later dismissed

2023-10-17 15:23 UTC, wvffle requested changes
Jak dla mnie to brakuje linkow w obu widokach by cofnac sie do logowania / rejestracji

2023-10-17 16:09 UTC, jwroblewska commented
> Jak dla mnie to brakuje linkow w obu widokach by cofnac sie do logowania / rejestracji

ogolnie to jak nad tym myśle to żeby dostać się do resetowania hasła to jedyny sposób to z okna logwania więc zawsze można cofnąć strone, a do zmiany hasła żeby sie dostać to albo panel klienta wyrażający chęc zmiany hasła ałbo link który dostaną na maila

ewentualnie w resetowaniu hasła pytanie czy "nie masz konta? zarejestruj się" ale to tylko to i tyle

2023-10-17 17:18 UTC, wvffle commented
> więc zawsze można cofnąć strone

Można, ale użytkownik jest debilem. W przeciwieństwie do developera oczywiście :)

> ewentualnie w resetowaniu hasła pytanie czy "nie masz konta? zarejestruj się" ale to tylko to i tyle

o to, to!

2023-10-18 21:39 UTC, jwroblewska commented
pnpm-lock.yaml krzyczy w paru miejscach, zmienić go do tego co było czy będziemy naprawiać? już nie pamiętam za co on odpowiadał

2023-10-19 10:31 UTC, wvffle requested changes

2023-10-19 10:31 UTC, wvffle commented on pages/reset-password-message.vue
> +    <!-- <UButton type="submit" class="mt-[8.5rem] mx-auto" block>
W sumie to po co te komentarze?

2023-10-19 10:38 UTC, wvffle commented
> pnpm-lock.yaml krzyczy w paru miejscach, zmienić go do tego co było czy będziemy naprawiać? już nie pamiętam za co on odpowiadał

Opisuje on aktualne drzewo zainstalowanych zaleznosci i pozwala pozniej odtworzyc identyczne drzewo przy instalacji

2023-10-20 10:49 UTC, closed without merging