Monika1909/Monika-designs
pb-iot/frontend pull request #51
Opened 2023-10-26 12:08 UTC by Monikaa1909

2023-10-26 14:10 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Historia środowisk/Historia środowisk - filtrowanie - najechanie na kalendarz.png
Moim zdaniem, jak sa 3 osoby, to powinny byc 3 avatary (bo sie mieszcza)

Jak sa 4 to 2 avatary i `+2`

2023-10-26 14:12 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Historia środowisk/Historia środowisk - filtrowanie.png
Padding do nagłówka `Data` w filtracji

2023-10-26 14:12 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Historia środowisk/Historia środowisk - wybrane środowisko.png
Sformatuj daty do j. polskiego

2023-10-26 14:13 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Lista szklarni - filtrowanie.png
Okrągłe checkboxy służą do wybrania jednej opcji z kilku. Użyj kwadratowych

2023-10-26 14:17 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Lista szklarni - w postaci card.png
Zastanawiam, się czy nie przerzucić przycisków od opcji wyświetlania na lewo, a filtrację zostawić po prawej tak, by były w 1 linii, a nie w dwóch.

Możnaby też użyć tu zwykłych przycisków, a dla opcji wyświetlania dać [Button Group](https://ui.nuxt.com/elements/button#group)

Do opcji wyświetlania trzeba też dodać jakiś label. Wystarczy 1 dla wszystkich 3. Np: `Wyświetlaj jako`

2023-10-26 14:19 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Lista szklarni - w postaci listy - najechanie na szklarnię.png
To musi być tabela z nazwą szklarni, przypisanymi osobami, jakimś statusem czy wszystko jest ok, czy jednak jakiś czujnik zawiódł i może czymś jeszcze.

2023-10-26 14:20 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Lista szklarni - w postaci mapy - najechanie na pineske.png
dodaj zielony przycisk na dole popupu `Zobacz szklarnię` czy coś podobnego.

2023-10-26 14:20 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Lista szklarni - w postaci mapy.png
Pineski zielone.

2023-10-26 14:22 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Statystyki szklarni/Statystyki szklarni w formie listy - filtrowanie - po zjechaniu paskiem w dół.png
To samo, kwadratowe inputy są od wielokrotnego wyboru, okrągłe od pojedynczego wyboru

2023-10-26 14:23 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Statystyki szklarni/Statystyki szklarni w formie listy - filtrowanie.png
@Monikaa1909 co to za trójkącik? Za co on ma odpowiadać?

2023-10-26 14:24 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Statystyki szklarni/Statystyki szklarni w formie listy - filtrowanie.png
Wydaje mi się, że wcześniejszy design info o szklarni daje więcej info.

2023-10-26 14:26 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Statystyki szklarni/Statystyki szklarni w formie listy - filtrowanie.png
Średnia musi być wyciągana z mniejszych zakresów czasowych niż tylko od dnia do dnia. Taka również, ale powiedzmy jeszcze musimy znać średnią z ostatniej godziny, czy 30 min.

2023-10-26 14:27 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Statystyki szklarni/Statystyki szklarni w formie listy.png
Wartości statystyk trzeba w jakiś sposób wyróżnić. Być może wystarczy przesunąć je do prawej, być może trzeba dać inny kolor.

2023-10-26 14:29 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Urządzenia szklarni/Urządzenia konkretnej szklarn - filtrowanie.png
Rodzaj i typ moim zdaniem mogą być wielokrotnego wyboru.

2023-10-26 14:32 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Urządzenia szklarni/Urządzenia konkretnej szklarni.png
Hmm... Daj `Wyłączone` żółte/pomarańczowe. Tak jakby to był warning. Dodaj jeszcze `Błąd urządzenia` / `Błąd komunikacji`, który jest czerwony i ma również czerwoną obwódkę  od 2 do 4px (wybierz sama grubość, nie wiem co będzie lepiej wyglądało).

2023-10-26 14:33 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Urządzenia szklarni/Urządzenia konkretnej szklarni.png
Do opcji urządzenia oraz szklarni trzeba dodać opcję `Zobacz dziennik zdarzeń` i widok, który pokazuje logi wszystkich urządzeń dla szklarni / pojedynczego urządzenia.

2023-10-26 14:35 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Środowisko szklarni/Środowisko konkretnej szklarni - edytowanie - po zjechaniu paskiem na dół.png
Wszędzie na `Docelowa temperatura` itd.

Jak chodzi o jednostki - [Możemy je wkomponować w input](https://ui.nuxt.com/forms/input#trailing)

2023-10-26 14:35 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Środowisko szklarni/Środowisko konkretnej szklarni - focus na edytuj.png
Też trzeba dać coś co powie, że to jest docelowe środowisko

2023-10-26 14:37 UTC, wvffle commented on designs/Zalogowany uzytkownik/Twój profil/Mój profil - usunięcie konta 1.png
Odwrotna kolejność przycisków i odwrotnie je pokoloruj. Anulowanie ma mieć czerwone tło, usunięcie białe

2023-10-26 14:56 UTC, wvffle commented
Ogółem, jak będą już gotowe widoki i zmergujemy PRkę, która modyfikuje jakiś zaimplementowany widok, to @Monikaa1909 będziesz musiała stworzyć nowe issue dla każdego zmodyfikowanego elementu.

@pb-iot/frontend Jak będziecie implementować widoki, to prócz rozbijania na layout i widok, rozbijajcie też na komponenty, czyli np widok szklarni to jeden komponent, którego używacie w widoku. Jak raz ma więcej informacji, raz mniej, to nie robicie dwóch komponentów, tylko dodajecie propa do istniejącego już komponentu.

2023-10-27 08:53 UTC, Monikaa1909 commented
Zajmę się tym wszystkim i wszystko poprawię, ale dopiero w poniedziałek :(

2023-11-03 11:47 UTC, wvffle requested changes

2023-11-03 11:47 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Urządzenia szklarni/Urządzenia konkretnej szklarni.png
@Monikaa1909 `wYłączone` powinno być żółte, `Włączone` może być zielone

2023-11-03 11:47 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Środowisko szklarni/Środowisko konkretnej szklarni - focus na edytuj.png
@Monikaa1909, może zamiast dac wszedzie `Docelowa temperatura`, to dać na górze `Docelowe środowisko`. zostawić normalnie `Temperatura`?

Przenies wartosci na prawo, jak w innych widokach.

2023-11-04 09:12 UTC, wvffle requested changes

2023-11-04 09:12 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Środowisko szklarni/Środowisko konkretnej szklarni - focus na edytuj.png
Przycisk `Edytuj` jako przycisk z Nuxt UI

2023-11-04 09:12 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Lista szklarni - w postaci mapy - najechanie na pineske.png
@Monikaa1909

2023-11-04 09:13 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Środowisko szklarni/Środowisko konkretnej szklarni - edytowanie - po zjechaniu paskiem na dół.png
@Monikaa1909

2023-11-04 09:13 UTC, wvffle commented on designs/Zalogowany uzytkownik/Listy szklarni/Statystyki szklarni/Statystyki szklarni w formie listy - filtrowanie.png
@Monikaa1909

2023-11-07 15:39 UTC, wvffle approved these changes

2023-11-07 16:49 UTC, SiwyKot41 approved these changes

2023-11-07 17:02 UTC, merged