changed colors of "cofnij" button to gray
pb-iot/frontend pull request #52
Opened 2023-10-26 19:00 UTC by OlaWrobe

-----
<a href="https://stackblitz.com/~/github/pb-iot/frontend/tree/OlaWrobe%2Fchanging-button-color-in-authentiation"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/pb-iot/frontend/tree/OlaWrobe%2Fchanging-button-color-in-authentiation)._

2023-10-26 21:33 UTC, wvffle requested changes

2023-10-26 21:33 UTC, wvffle commented on pages/reset-password-message.vue
> +        class="bg-gray-500 hover:bg-gray-700"
Masz na to odpowiedni prop :)

https://ui.nuxt.com/elements/button#gray

2023-10-27 08:44 UTC, SiwyKot41 approved these changes

2023-11-08 09:15 UTC, wvffle approved these changes

2023-11-08 09:16 UTC, merged