Monika/designs
pb-iot/frontend pull request #93
Opened 2023-11-29 14:45 UTC by Monikaa1909

2023-11-30 08:55 UTC, wvffle requested changes

2023-11-30 08:55 UTC, wvffle commented on designs/Zalogowany uzytkownik/Lokacje/Edycja lokacji.png
raczej mapka z pineska do przeciagniecia

2023-12-01 13:45 UTC, Monikaa1909 commented on designs/Zalogowany uzytkownik/Lokacje/Edycja lokacji.png
Tylko mapka czy zostawić formsy i przy przeciąganiu zmieniają się w nich dane/przy zmianie danych ręcznie pineska się przesunie?

2023-12-01 23:41 UTC, wvffle commented on designs/Zalogowany uzytkownik/Lokacje/Edycja lokacji.png
mapka + nazwa

2023-12-04 21:13 UTC, wvffle approved these changes

2024-01-16 16:39 UTC, OlaWrobe approved these changes

2024-01-16 16:39 UTC, merged